# -*- coding: utf-8 -*-
"""ConsolidadoM4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKmQyt2T16cmqKcU2zP4CRppJUXmzjxh
"""

import pandas as pd

# Cargar archivo Excel
archivo = "olimpicos.csv"
df = pd.read_csv(archivo)
df.columns = [col.strip() for col in df.columns]

# Corregir caracteres especiales
df["Deporte"] = df["Deporte"].str.encode("latin1").str.decode("utf-8", errors="ignore")

# Mostrar todos los datos
print("\n Datos completos de atletas olímpicos:\n")
print(df.to_string(index=False))

# Estadísticas generales
print("\n Estadísticas generales:")
print(f"- Edad promedio: {round(df['Edad'].mean(), 1)} años")
print(f"- Altura promedio: {round(df['Altura_cm'].mean(), 1)} cm")
print(f"- Peso promedio: {round(df['Peso_kg'].mean(), 1)} kg")
print(f"- Medallas totales: {df['Medallas_Totales'].sum()}")

# Atleta con más medallas
top_medallas = df.loc[df['Medallas_Totales'].idxmax()]
print(f"\n Atleta con más medallas: {top_medallas['Atleta']} ({top_medallas['Medallas_Totales']} medallas)")

# Promedio de entrenamientos por deporte
print("\n🏃‍♂️ Promedio de entrenamientos semanales por deporte:")
print(df.groupby("Deporte")["Entrenamientos_Semanales"].mean().round(1))

# Medallas por país
print("\n Medallas totales por país:")
print(df.groupby("Pais")["Medallas_Totales"].sum().sort_values(ascending=False))

# Exportar resumen a CSV (opcional)
resumen = {
    "Edad promedio": [round(df['Edad'].mean(), 1)],
    "Altura promedio": [round(df['Altura_cm'].mean(), 1)],
    "Peso promedio": [round(df['Peso_kg'].mean(), 1)],
    "Medallas totales": [df['Medallas_Totales'].sum()],
    "Atleta con más medallas": [top_medallas['Atleta']]
}
pd.DataFrame(resumen).to_csv("resumen_olimpicos.csv", index=False)
print("\n✅ Resumen exportado a 'resumen_olimpicos.csv'")